# Generated by Django 2.2 on 2021-03-18 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=128, verbose_name='专辑名')),
                ('album_picture', models.ImageField(blank=True, upload_to='avatar/%Y%m%d/', verbose_name='专辑封面')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('singer', models.CharField(max_length=128, verbose_name='歌手')),
                ('description', models.TextField(default='', verbose_name='专辑简介')),
            ],
            options={
                'verbose_name': '专辑信息管理',
                'verbose_name_plural': '专辑信息管理',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='AlbumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='2', max_length=128, verbose_name='评论内容')),
                ('sender', models.CharField(max_length=128, verbose_name='评论人')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
        migrations.CreateModel(
            name='AllLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=128, verbose_name='歌单名')),
                ('song_count', models.IntegerField(default=0, verbose_name='歌曲数')),
                ('list_picture', models.ImageField(blank=True, upload_to='avatar/%Y%m%d/', verbose_name='歌单封面')),
                ('description', models.TextField(default='', verbose_name='歌单简介')),
                ('play_count', models.IntegerField(default=0, verbose_name='播放量')),
            ],
            options={
                'verbose_name': '歌单信息管理',
                'verbose_name_plural': '歌单信息管理',
                'ordering': ['-play_count'],
            },
        ),
        migrations.CreateModel(
            name='ListComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='评论内容')),
                ('sender', models.CharField(max_length=128, verbose_name='评论人')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.AllLists')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=128, verbose_name='歌曲名')),
                ('song_url', models.FileField(upload_to='song/%Y%m%d/', verbose_name='歌曲资源')),
                ('play_count', models.IntegerField(default=0, verbose_name='播放量')),
                ('lyric', models.FileField(blank=True, upload_to='song/lyric/%Y%m%d', verbose_name='歌词')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
            options={
                'verbose_name': '歌曲信息管理',
                'verbose_name_plural': '歌曲信息管理',
                'ordering': ['-play_count'],
            },
        ),
        migrations.CreateModel(
            name='SongComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='评论内容')),
                ('sender', models.CharField(max_length=128, verbose_name='评论人')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('is_active', models.IntegerField(default=1, verbose_name='是否激活')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/%Y%m%d/', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('follow_count', models.IntegerField(default=0, verbose_name='关注数')),
                ('fan_count', models.IntegerField(default=0, verbose_name='粉丝数')),
            ],
            options={
                'verbose_name': '用户信息管理',
                'verbose_name_plural': '用户信息管理',
            },
        ),
        migrations.CreateModel(
            name='TheList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_lists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.AllLists')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
            ],
            options={
                'verbose_name': '歌单歌曲信息管理',
                'verbose_name_plural': '歌单歌曲信息管理',
            },
        ),
        migrations.CreateModel(
            name='SongReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='回复内容')),
                ('replier', models.CharField(max_length=128, verbose_name='回复人')),
                ('reply_time', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.SongComment')),
            ],
        ),
        migrations.CreateModel(
            name='ListReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='回复内容')),
                ('replier', models.CharField(max_length=128, verbose_name='回复人')),
                ('reply_time', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.ListComment')),
            ],
        ),
        migrations.CreateModel(
            name='LikeSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.User')),
            ],
            options={
                'verbose_name': '喜爱歌曲信息管理',
                'verbose_name_plural': '喜爱歌曲信息管理',
            },
        ),
        migrations.CreateModel(
            name='LikeLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.AllLists')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.User')),
            ],
            options={
                'verbose_name': '喜爱歌单信息管理',
                'verbose_name_plural': '喜爱歌单信息管理',
            },
        ),
        migrations.CreateModel(
            name='LikeAlbums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.User')),
            ],
            options={
                'verbose_name': '喜爱专辑信息管理',
                'verbose_name_plural': '喜爱专辑信息管理',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.User')),
            ],
            options={
                'verbose_name': '用户关注信息管理',
                'verbose_name_plural': '用户关注信息管理',
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.User')),
            ],
            options={
                'verbose_name': '用户粉丝信息管理',
                'verbose_name_plural': '用户粉丝信息管理',
            },
        ),
        migrations.AddField(
            model_name='alllists',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.User', verbose_name='创建者'),
        ),
        migrations.CreateModel(
            name='AlbumReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='回复内容')),
                ('replier', models.CharField(max_length=128, verbose_name='回复人')),
                ('reply_time', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.AlbumComment')),
            ],
        ),
    ]
