# Generated by Django 2.2 on 2021-03-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210319_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='banner',
            field=models.ImageField(blank=True, upload_to='avatar/%Y%m%d/', verbose_name='专辑轮播图'),
        ),
    ]
