# Generated by Django 2.2 on 2021-03-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_emailverifyrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
