# Generated by Django 2.2 on 2021-03-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20210330_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongCommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.SongComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.User')),
            ],
        ),
    ]
