# Generated by Django 2.2 on 2021-03-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_songcommentlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.ListComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.User')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumCommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.AlbumComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.User')),
            ],
        ),
    ]
