# Generated by Django 2.2 on 2021-03-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_albumcommentlike_listcommentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllists',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='歌单简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=0, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='性别'),
        ),
    ]
