# Generated by Django 2.2 on 2021-04-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20210403_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcomment',
            name='sender_id',
            field=models.IntegerField(null=True, verbose_name='评论人id'),
        ),
        migrations.AddField(
            model_name='listcomment',
            name='sender_id',
            field=models.IntegerField(null=True, verbose_name='评论人id'),
        ),
        migrations.AddField(
            model_name='songcomment',
            name='sender_id',
            field=models.IntegerField(null=True, verbose_name='评论人id'),
        ),
    ]
