# Generated by Django 2.2 on 2021-04-04 05:17

from django.db import migrations, models
import music.fields


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20210404_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcomment',
            name='sender',
            field=models.CharField(blank=True, max_length=128, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='listcomment',
            name='sender',
            field=models.CharField(blank=True, max_length=128, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='songcomment',
            name='sender',
            field=models.CharField(blank=True, max_length=128, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=music.fields.RestrictedFileField(blank=True, upload_to='avatar/%Y%m%d/', verbose_name='头像'),
        ),
    ]
